//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmalaTu.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido
    {
        public int id_pedido { get; set; }
        public string nombre_cliente { get; set; }
        public string direccion { get; set; }
        public string bebida { get; set; }
        public string servir { get; set; }
        public int id_pizza { get; set; }
        public int descuento { get; set; }
        public int total { get; set; }
    
        public virtual pizza pizza { get; set; }
    }
}
