//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmalaTu.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class pizza
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pizza()
        {
            this.pedido = new HashSet<pedido>();
        }
    
        public int id { get; set; }
        public string tipo_pago { get; set; }
        public string masa { get; set; }
        public string tamaño { get; set; }
        public string dos_por_uno { get; set; }
        public string nombre_pizza { get; set; }
        public int precio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedido> pedido { get; set; }
    }
}
